// ✅ SEO Metadata - Auto-generated by SEO Agent
export const metadata = {
  title: "Careers - Complete Bawdicsoft Guide 2024",
  description: "Learn everything about careers with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
  keywords: [
    "with",
    "bawdicsoft",
    "your",
    "experience",
    "responsibilities",
    "requirements"
  ],
  alternates: {
    canonical: "https://www.bawdicsoft.com/careers"
  },
  robots: "index, follow",
  openGraph: {
    title: "Careers - Complete Bawdicsoft Guide 2024",
    description: "Learn everything about careers with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
    url: "https://www.bawdicsoft.com/careers",
    siteName: "Bawdicsoft",
    images: [
      {
        url: "https://www.bawdicsoft.com/careers/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Careers - Complete Bawdicsoft Guide 2024"
      }
    ],
    type: "website"
  },
  twitter: {
    card: "summary_large_image",
    title: "Careers - Complete Bawdicsoft Guide 2024",
    description: "Learn everything about careers with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
    images: ["https://www.bawdicsoft.com/careers/twitter-image.jpg"]
  }
};




import FormSection from "@/components/careers/form";
import HeroSection from "@/components/careers/heroSectin";
import RecruitmentSection from "@/components/careers/recruitmentSection";
import GetInTouchWithUs from "@/components/contactUs/getInTouch";
import { FC } from "react"
interface careersProps {}

const Careers :FC<careersProps> = () => {
return (<div>
 <HeroSection />
 <RecruitmentSection/>
 <FormSection />
 <GetInTouchWithUs />
</div>)
}
export default Careers;
