// ✅ SEO Metadata - Auto-generated by SEO Agent
export const metadata = {
  title: "Contact Us Bawdicsoft LLC Pvt. Ltd.",
  description: "Learn everything about contact us with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
  keywords: [
    "bawdicsoft",
    "your",
    "with",
    "contact",
    "services",
    "about"
  ],
  alternates: {
    canonical: "https://www.bawdicsoft.com/contact-us"
  },
  robots: "index, follow",
  openGraph: {
    title: "Contact Us Bawdicsoft LLC Pvt. Ltd.",
    description: "Learn everything about contact us with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
    url: "https://www.bawdicsoft.com/contact-us",
    siteName: "Bawdicsoft",
    images: [
      {
        url: "https://www.bawdicsoft.com/contact-us/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Contact Us Bawdicsoft LLC Pvt. Ltd."
      }
    ],
    type: "website"
  },
  twitter: {
    card: "summary_large_image",
    title: "Contact Us Bawdicsoft LLC Pvt. Ltd.",
    description: "Learn everything about contact us with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
    images: ["https://www.bawdicsoft.com/contact-us/twitter-image.jpg"]
  }
};



import FormSection from "@/components/contactUs/formSection";
import GetInTouchWithUs from "@/components/contactUs/getInTouch";
import HeroSection from "@/components/contactUs/heroSection";
import MapSection from "@/components/contactUs/mapSection";
import { FC } from "react"
interface contactUsProps {}

const ContactUs :FC<contactUsProps> = () => {
return (<div>
  <HeroSection />
  <MapSection />
  <FormSection />
  <GetInTouchWithUs />
</div>)
}
export default ContactUs;
