// ✅ SEO Metadata - Auto-generated by SEO Agent
export const metadata = {
  title: "About BawdicSoft | AI & Software Agency Founded 2018",
  description: "BawdicSoft was founded in 2018 by Syed Bilal Hashmi in Karachi. A 22-person ISO 27001 certified team delivering AI, blockchain, and web solutions globally.",
  keywords: [
    "about BawdicSoft, Syed Bilal Hashmi, software agency Karachi, AI company Pakistan"
  ],
  alternates: {
    canonical: "https://www.bawdicsoft.com/about-us"
  },
  robots: "index, follow",
  openGraph: {
    title: "About Us - Complete Bawdicsoft Guide 2024",
    description: "Learn everything about about us with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
    url: "https://www.bawdicsoft.com/about-us",
    siteName: "Bawdicsoft",
    images: [
      {
        url: "https://www.bawdicsoft.com/about-us/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "About Us - Complete Bawdicsoft Guide 2024"
      }
    ],
    type: "website"
  },
  twitter: {
    card: "summary_large_image",
    title: "About Us - Complete Bawdicsoft Guide 2024",
    description: "Learn everything about about us with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
    images: ["https://www.bawdicsoft.com/about-us/twitter-image.jpg"]
  }
};



import DocumtentsSectins from "@/components/aboutUs/document";
import HeroSection from "@/components/aboutUs/heroSection";
import OurSevices from "@/components/aboutUs/ourServices";
import OurVisionMission from "@/components/aboutUs/ourVisionMision";
import OurTeam from "@/components/home/team";
import { FC } from "react";

interface aboutUsProps {}

 const AboutUs :FC<aboutUsProps> = () => {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: `{
  "@context": "https://schema.org",
  "@type": "WebPage",
  "name": "About Us - Complete Bawdicsoft Guide 2024",
  "description": "Learn everything about about us with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
  "url": "https://www.bawdicsoft.com/about-us",
  "publisher": {
    "@type": "Organization",
    "name": "Bawdicsoft"
  }
}` }}
      />
   <div>
    <HeroSection />
    <DocumtentsSectins />
    <OurVisionMission />
    <OurTeam />
    <OurSevices />
   </div>
    </>
  )
}

export default AboutUs;
