// ✅ SEO Metadata
// ✅ SEO Metadata
export const metadata = {
  title: "BawdicSoft",
  description: "Generated by BawdicSoft",
  keywords: [
    "your",
    "user",
    "application",
    "bawdicsoft",
    "design",
    "experience",
    "like",
    "while"
  ],
  openGraph: {
    title: "BawdicSoft",
    description: "Generated by BawdicSoft",
    url: "https://bawdicsoft-new-website.vercel.app/web-application",
    siteName: "Sigmantarian",
    images: [
      {
        url: "https://bawdicsoft-new-website.vercel.app/web-application/opengraph-image.jpg",
        width: 1200,
        height: 630,
        alt: "BawdicSoft"
      }
    ],
    type: "website"
  },
  twitter: {
    card: "summary_large_image",
    title: "BawdicSoft",
    description: "Generated by BawdicSoft",
    images: ["https://bawdicsoft-new-website.vercel.app/web-application/twitter-image.jpg"]
  }
};




import ApiIntegration from "@/components/services/webApplication/apiIntegartion";
import BackendSection from "@/components/services/webApplication/backendSection";
import FrontEndSection from "@/components/services/webApplication/frontendSection";
import HeroSection from "@/components/services/webApplication/heroSection";
import UiUxSection from "@/components/services/webApplication/uiUx";
import { FC } from "react"
interface WebApplicationProps {}

const WebApplication :FC<WebApplicationProps> = () => {
return (<div>
<HeroSection />
<UiUxSection />
<BackendSection />
<FrontEndSection />
<ApiIntegration />
</div>)
}
export default WebApplication;