// ✅ SEO Metadata - Auto-generated by SEO Agent
export const metadata = {
  title: "Portfolio | AI & Blockchain Projects — BawdicSoft",
  description: "Explore BawdicSoft's portfolio — AI detection tools, DeFi platforms, NFT marketplaces, and enterprise web apps built for global clients.",
  keywords: [
    "AI portfolio, blockchain portfolio, Deep-Trace AI, CyberCity AI, NFT marketplace, DeFi platform"
  ],
  alternates: {
    canonical: "https://www.bawdicsoft.com/portfolio"
  },
  robots: "index, follow",
  openGraph: {
    title: "Portfolio - Complete Bawdicsoft Guide 2024",
    description: "Learn everything about portfolio with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
    url: "https://www.bawdicsoft.com/portfolio",
    siteName: "Bawdicsoft",
    images: [
      {
        url: "https://www.bawdicsoft.com/portfolio/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Portfolio - Complete Bawdicsoft Guide 2024"
      }
    ],
    type: "website"
  },
  twitter: {
    card: "summary_large_image",
    title: "Portfolio - Complete Bawdicsoft Guide 2024",
    description: "Learn everything about portfolio with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
    images: ["https://www.bawdicsoft.com/portfolio/twitter-image.jpg"]
  }
};



import HeroSection from "@/components/portFolio/heroSection";
// import OurWorks from "@/components/portFolio/ourWorks";
import ProductServices from "@/components/portFolio/porductPortFolio";
import PortFolioSection from "@/components/portFolio/portFoliSection";
import { FC } from "react"
interface portFolioProps {}

const PortFolio :FC<portFolioProps> = () => {
return (<div>
<HeroSection />
<ProductServices />
{/* <OurWorks /> */}
<PortFolioSection />
</div>)
}
export default PortFolio;
