// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/navbar";
// import Footer from "@/components/footer";
// import Script from "next/script";
// import WhatsAppButton from '@/components/WhatsAppButton';

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "BawdicSoft",
//   description: "Generated by BawdicSoft",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <head>
//         <Script
//           strategy="afterInteractive"
//           src="https://www.googletagmanager.com/gtag/js?id=G-HDV25HSV2B"
//         />
//         <Script
//           id="gtag-init"
//           strategy="lazyOnload"
//           dangerouslySetInnerHTML={{
//             __html: `
//               window.dataLayer = window.dataLayer || [];
//               function gtag(){dataLayer.push(arguments);}
//               gtag('js', new Date());
//               gtag('config', 'G-HDV25HSV2B');
//             `,
//           }}
//         />
//       </head>
//       <body className={inter.className}>
//         <Navbar />
//         {children}
//         <WhatsAppButton/>
//         <Footer />
//       </body>
//     </html>
//   );
// }







import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Script from "next/script";
import WhatsAppButton from '@/components/WhatsAppButton';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BawdicSoft",
  description: "Generated by BawdicSoft",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Google Analytics Scripts (Moved to body for Next.js App Router best practices) */}
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-HDV25HSV2B"
        />
        <Script
          id="gtag-init"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-HDV25HSV2B');
            `,
          }}
        />
        
        <Navbar />
        <main>
          {children}
        </main>
        <WhatsAppButton />
        <Footer />
      </body>
    </html>
  );
}