// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/navbar";
// import Footer from "@/components/footer";
// import Script from "next/script";
// import WhatsAppButton from '@/components/WhatsAppButton';

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "BawdicSoft",
//   description: "Generated by BawdicSoft",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <head>
//         <Script
//           strategy="afterInteractive"
//           src="https://www.googletagmanager.com/gtag/js?id=G-HDV25HSV2B"
//         />
//         <Script
//           id="gtag-init"
//           strategy="lazyOnload"
//           dangerouslySetInnerHTML={{
//             __html: `
//               window.dataLayer = window.dataLayer || [];
//               function gtag(){dataLayer.push(arguments);}
//               gtag('js', new Date());
//               gtag('config', 'G-HDV25HSV2B');
//             `,
//           }}
//         />
//       </head>
//       <body className={inter.className}>
//         <Navbar />
//         {children}
//         <WhatsAppButton/>
//         <Footer />
//       </body>
//     </html>
//   );
// }





// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import SiteChrome from "@/components/SiteChrome";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BawdicSoft",
  description: "Generated by BawdicSoft",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* ===== GOOGLE ANALYTICS (GA4) ===== */}
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-HDV25HSV2B"
        />
        <Script
          id="gtag-init"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-HDV25HSV2B');
            `,
          }}
        />

        <SiteChrome>{children}</SiteChrome>


        {/* ===== 🔥 COOKIE CONSENT BANNER (Left Side, White, Accept/Reject) ===== */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                // 📌 1. Check if user has already made a choice
                const consent = localStorage.getItem('bawdic_cookie_consent');

                // 📌 2. If already accepted, run tracking immediately
                if (consent === 'accepted') {
                  startTracking();
                  return;
                }

                // 📌 3. If rejected or no choice, show the banner
                if (consent !== 'rejected') {
                  showConsentBanner();
                }

                // 📌 4. Cookie Consent Banner HTML (Left side, White)
                function showConsentBanner() {
                  const banner = document.createElement('div');
                  banner.id = 'cookie-consent-banner';
                  banner.style.cssText = \`
                    position: fixed;
                    bottom: 24px;
                    left: 24px;
                    background: #ffffff;
                    color: #1e293b;
                    padding: 20px 28px;
                    border-radius: 16px;
                    box-shadow: 0 12px 48px rgba(0,0,0,0.15);
                    border: 1px solid #e2e8f0;
                    z-index: 999999;
                    max-width: 420px;
                    font-family: system-ui, -apple-system, sans-serif;
                    transition: all 0.3s ease;
                  \`;

                  banner.innerHTML = \`
                    <div style="display: flex; flex-direction: column; gap: 14px;">
                      <div>
                        <div style="display: flex; align-items: center; gap: 10px; margin-bottom: 6px;">
                          <span style="font-size: 22px;">🍪</span>
                          <span style="font-weight: 700; font-size: 16px; color: #0f172a;">
                            We use cookies
                          </span>
                        </div>
                        <p style="font-size: 13px; color: #475569; line-height: 1.6; margin: 0;">
                          We use cookies to enhance your experience, analyze site traffic, and personalize content. 
                          By clicking "Accept", you agree to our use of cookies.
                        </p>
                      </div>
                      <div style="display: flex; gap: 12px; margin-top: 4px;">
                        <button 
                          id="cookie-accept"
                          style="
                            flex: 1;
                            background: #0f172a;
                            color: white;
                            border: none;
                            padding: 10px 20px;
                            border-radius: 10px;
                            font-weight: 600;
                            font-size: 14px;
                            cursor: pointer;
                            transition: background 0.2s;
                          "
                          onmouseover="this.style.background='#1e293b'"
                          onmouseout="this.style.background='#0f172a'"
                        >
                          Accept
                        </button>
                        <button 
                          id="cookie-reject"
                          style="
                            flex: 1;
                            background: #f1f5f9;
                            color: #1e293b;
                            border: none;
                            padding: 10px 20px;
                            border-radius: 10px;
                            font-weight: 600;
                            font-size: 14px;
                            cursor: pointer;
                            transition: background 0.2s;
                          "
                          onmouseover="this.style.background='#e2e8f0'"
                          onmouseout="this.style.background='#f1f5f9'"
                        >
                          Reject
                        </button>
                      </div>
                      <div style="font-size: 11px; color: #94a3b8; margin-top: 2px; text-align: center; border-top: 1px solid #f1f5f9; padding-top: 10px;">
                        You can change your preferences anytime in settings.
                      </div>
                    </div>
                  \`;

                  document.body.appendChild(banner);

                  // Accept button
                  document.getElementById('cookie-accept').addEventListener('click', function() {
                    localStorage.setItem('bawdic_cookie_consent', 'accepted');
                    banner.style.opacity = '0';
                    banner.style.transform = 'translateX(-24px)';
                    setTimeout(() => {
                      if (banner.parentNode) banner.remove();
                    }, 300);
                    startTracking();
                  });

                  // Reject button
                  document.getElementById('cookie-reject').addEventListener('click', function() {
                    localStorage.setItem('bawdic_cookie_consent', 'rejected');
                    banner.style.opacity = '0';
                    banner.style.transform = 'translateX(-24px)';
                    setTimeout(() => {
                      if (banner.parentNode) banner.remove();
                    }, 300);
                    // No tracking
                  });
                }

                // 📌 5. Tracking Function (Only runs after Accept)
                function startTracking() {
                  // Cookie Helpers
                  function getCookie(name) {
                    const value = "; " + document.cookie;
                    const parts = value.split("; " + name + "=");
                    if (parts.length === 2) return parts.pop().split(";").shift();
                    return null;
                  }
                  function setCookie(name, value, days) {
                    const date = new Date();
                    date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
                    document.cookie = name + "=" + value + "; path=/; expires=" + date.toUTCString();
                  }

                  // Session ID
                  let sessionId = getCookie('bawdic_session_id');
                  if (!sessionId) {
                    sessionId = 'session_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);
                    setCookie('bawdic_session_id', sessionId, 30);
                  }

                  // IP API call
                 fetch('/api/ip')
                    .then(res => res.json())
                    .then(data => {
                      fetch('/api/track', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({
                          ip: data.query || data.ip,
                          company: data.isp || data.org || 'Unknown',
                          city: data.city || 'Unknown',
                          country: data.country || data.country_name || 'Location',
                          device: navigator.userAgent,
                          sessionId: sessionId,
                          page: window.location.href,
                          referrer: document.referrer || 'Direct'
                        })
                      }).catch(err => console.log('Track error:', err));

                      // Toast Notification (After Accept)
                      const city = data.city || 'Unknown';
                      const country = data.country || 'Location';
                      const company = data.isp || 'Guest';

                      const toast = document.createElement('div');
                      toast.style.cssText = \`
                        position: fixed;
                        bottom: 24px;
                        right: 24px;
                        background: #1e293b;
                        color: #f8fafc;
                        padding: 12px 20px;
                        border-radius: 14px;
                        font-size: 13px;
                        font-family: system-ui, -apple-system, sans-serif;
                        z-index: 99999;
                        box-shadow: 0 12px 40px rgba(0,0,0,0.35);
                        border: 1px solid #334155;
                        backdrop-filter: blur(8px);
                        max-width: 360px;
                        opacity: 0;
                        transform: translateY(24px) scale(0.96);
                        transition: all 0.4s cubic-bezier(0.34, 1.56, 0.64, 1);
                        pointer-events: none;
                      \`;
                      toast.innerHTML = \`
                        <div style="display: flex; align-items: center; gap: 10px;">
                          <span style="font-size: 20px;">🍪</span>
                          <div>
                            <div style="font-weight: 600; font-size: 13px; color: #e2e8f0;">Tracking Active</div>
                            <div style="font-size: 12px; color: #94a3b8; margin-top: 2px;">
                              Detected: \${city}, \${country} · \${company}
                            </div>
                          </div>
                          <span style="font-size: 10px; background: #334155; padding: 2px 8px; border-radius: 20px; color: #94a3b8; margin-left: 4px;">
                            Cookie Set
                          </span>
                        </div>
                      \`;
                      document.body.appendChild(toast);
                      setTimeout(() => { toast.style.opacity = '1'; toast.style.transform = 'translateY(0) scale(1)'; }, 200);
                      setTimeout(() => {
                        toast.style.opacity = '0';
                        toast.style.transform = 'translateY(24px) scale(0.96)';
                        setTimeout(() => { if (toast.parentNode) toast.remove(); }, 400);
                      }, 5000);
                    })
                    .catch(err => console.log('IP fetch error:', err));
                }
              })();
            `
          }}
        />
       
      </body>
    </html>
  );
}