// ✅ SEO Metadata - Auto-generated by SEO Agent
export const metadata = {
  title: "BawdicSoft | AI, Blockchain & Web Development Agency — Karachi",
  description: "BawdicSoft delivers enterprise-grade AI solutions, blockchain development, and web applications. 250+ projects. 15+ countries.  certified. Get a free consultation",
  keywords: ["AI agency Karachi, blockchain development, web3 development, software agency Pakistan, AI automation"],
  alternates: {
    canonical: "https://www.bawdicsoft.com/"
  },
  robots: "index, follow",
  openGraph: {
    title: "Bawdicsoft LLC Pvt. Ltd.",
    description: "Learn everything about  with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
    url: "https://www.bawdicsoft.com/",
    siteName: "Bawdicsoft",
    images: [
      {
        url: "https://www.bawdicsoft.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Bawdicsoft LLC Pvt. Ltd."
      }
    ],
    type: "website"
  },
  twitter: {
    card: "summary_large_image",
    title: "Bawdicsoft LLC Pvt. Ltd.",
    description: "Learn everything about  with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
    images: ["https://www.bawdicsoft.com/twitter-image.jpg"]
  }
};

import Footer from "@/components/footer";
// import Expertise from "@/components/home/expertiseweb";
// import OurTeam from "@/components/home/team";
import HeroSection from "@/components/home/heroSection";
// import OfferSection from "@/components/home/offer";
import SevicesOffer from "@/components/home/servicesOffer";
import Navbar from "@/components/navbar";
import TrustSignalsSection from "@/components/home/trustsignal";
import EnterprisePainPointsSection from "@/components/home/enterprise";
import WhyBawdicSoftSection from "@/components/home/whybawdicsoft";
import CaseStudiesSection from "@/components/home/casestudies";
import HowWeWorkSection from "@/components/home/howwework";
import SecurityComplianceSection from "@/components/home/security";
import Cta from "@/components/home/cta";
import AIProducts from "@/components/AIproducts/AIProducts";
import LeadMagnet from "@/components/home/LeadMagnet";
import ExitPopup from '@/components/ExitPopup';
import StickyHeader from '@/components/StickyHeader';

export default function Home() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: `{
  "@context": "https://schema.org",
  "@type": "WebPage",
  "name": "Bawdicsoft LLC Pvt. Ltd.",
  "description": "Learn everything about  with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
  "url": "https://www.bawdicsoft.com/",
  "publisher": {
    "@type": "Organization",
    "name": "Bawdicsoft"
  }
}` }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: `{
  "@context": "https://schema.org",
  "@type": "WebPage",
  "name": "Bawdicsoft LLC Pvt. Ltd.",
  "description": "Learn everything about  with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
  "url": "https://www.bawdicsoft.com/",
  "publisher": {
    "@type": "Organization",
    "name": "Bawdicsoft"
  }
}` }}
      />
      <StickyHeader />
      <HeroSection />
      <TrustSignalsSection />
      <AIProducts />
      {/* <LeadMagnet /> */}
      <EnterprisePainPointsSection />
      <WhyBawdicSoftSection />

      {/* <CaseStudiesSection /> */}
      <HowWeWorkSection />
      <SecurityComplianceSection />
      <Cta />
      <ExitPopup />
      {/* <OfferSection />
  <Expertise /> */}
      {/* <SevicesOffer /> */}
      {/* <OurTeam /> */}
    </>
  )
}
