// ✅ SEO Metadata - Auto-generated by SEO Agent
export const metadata = {
  title: "- Complete Bawdicsoft Guide 2024",
  description: "Learn everything about  with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
  keywords: [
    "security",
    "enterprise",
    "with",
    "development",
    "your",
    "data"
  ],
  alternates: {
    canonical: "https://www.bawdicsoft.com/"
  },
  robots: "index, follow",
  openGraph: {
    title: "- Complete Bawdicsoft Guide 2024",
    description: "Learn everything about  with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
    url: "https://www.bawdicsoft.com/",
    siteName: "Bawdicsoft",
    images: [
      {
        url: "https://www.bawdicsoft.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "- Complete Bawdicsoft Guide 2024"
      }
    ],
    type: "website"
  },
  twitter: {
    card: "summary_large_image",
    title: "- Complete Bawdicsoft Guide 2024",
    description: "Learn everything about  with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
    images: ["https://www.bawdicsoft.com/twitter-image.jpg"]
  }
};
// ✅ SEO Metadata - Auto-generated by SEO Agent


import Footer from "@/components/footer";
// import Expertise from "@/components/home/expertiseweb";
// import OurTeam from "@/components/home/team";
import HeroSection from "@/components/home/heoSection";
// import OfferSection from "@/components/home/offer";
import SevicesOffer from "@/components/home/servicesOffer";
import Navbar from "@/components/navbar";
import TrustSignalsSection from "@/components/home/trustsignal";
import EnterprisePainPointsSection from "@/components/home/enterprise";
import WhyBawdicSoftSection from "@/components/home/whybawdicsoft";
import CaseStudiesSection from "@/components/home/casestudies";
import HowWeWorkSection from "@/components/home/howwework";
import SecurityComplianceSection from "@/components/home/security";
import Cta from "@/components/home/cta";

export default function Home() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: `{
  "@context": "https://schema.org",
  "@type": "WebPage",
  "name": "- Complete Bawdicsoft Guide 2024",
  "description": "Learn everything about  with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
  "url": "https://www.bawdicsoft.com/",
  "publisher": {
    "@type": "Organization",
    "name": "Bawdicsoft"
  }
}` }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: `{
  "@context": "https://schema.org",
  "@type": "WebPage",
  "name": "- Complete Bawdicsoft Guide 2024",
  "description": "Learn everything about  with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
  "url": "https://www.bawdicsoft.com/",
  "publisher": {
    "@type": "Organization",
    "name": "Bawdicsoft"
  }
}` }}
      />
  <HeroSection />
  <TrustSignalsSection />
  <EnterprisePainPointsSection />
  <WhyBawdicSoftSection />
  {/* <CaseStudiesSection /> */}
  <HowWeWorkSection />
  <SecurityComplianceSection />
  <Cta />
  {/* <OfferSection />
  <Expertise /> */}
  {/* <SevicesOffer /> */}
  {/* <OurTeam /> */}
    </>
  )
}
