// ✅ SEO Metadata - Auto-generated by SEO Agent
export const metadata = {
  title: "Services - Complete Bawdicsoft Guide 2024",
  description: "Learn everything about services with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
  keywords: [
    "your",
    "development",
    "application",
    "website",
    "that",
    "blockchain"
  ],
  alternates: {
    canonical: "https://www.bawdicsoft.com/services"
  },
  robots: "index, follow",
  openGraph: {
    title: "Services - Complete Bawdicsoft Guide 2024",
    description: "Learn everything about services with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
    url: "https://www.bawdicsoft.com/services",
    siteName: "Bawdicsoft",
    images: [
      {
        url: "https://www.bawdicsoft.com/services/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Services - Complete Bawdicsoft Guide 2024"
      }
    ],
    type: "website"
  },
  twitter: {
    card: "summary_large_image",
    title: "Services - Complete Bawdicsoft Guide 2024",
    description: "Learn everything about services with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
    images: ["https://www.bawdicsoft.com/services/twitter-image.jpg"]
  }
};
import SevicesOffer from "@/components/home/servicesOffer";
import Expertise from "@/components/home/expertiseweb";

const Services = () => {
  return( 
  <div>
    <SevicesOffer />
    <Expertise />
  </div>
    )
};

export default Services;