// ✅ SEO Metadata - Auto-generated by SEO Agent
export const metadata = {
  title: "Our Services | AI, Blockchain & Web Development — BawdicSoft",
  description: "From AI automation and smart contracts to full-stack web apps — BawdicSoft builds scalable, secure digital solutions for startups and enterprises worldwide.",
  keywords: [
    "AI development services, smart contract development, DeFi development, NLP solutions, computer vision"
  ],
  alternates: {
    canonical: "https://www.bawdicsoft.com/services"
  },
  robots: "index, follow",
  openGraph: {
    title: "Services Bawdicsoft LLC Pvt. Ltd.",
    description: "Learn everything about services with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
    url: "https://www.bawdicsoft.com/services",
    siteName: "Bawdicsoft",
    images: [
      {
        url: "https://www.bawdicsoft.com/services/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Services Bawdicsoft LLC Pvt. Ltd."
      }
    ],
    type: "website"
  },
  twitter: {
    card: "summary_large_image",
    title: "Services Bawdicsoft LLC Pvt. Ltd.",
    description: "Learn everything about services with our complete guide. Get expert tips, best practices, and step-by-step instructions from Bawdicsoft.",
    images: ["https://www.bawdicsoft.com/services/twitter-image.jpg"]
  }
};
import SevicesOffer from "@/components/home/servicesOffer";
import Expertise from "@/components/home/expertiseweb";

const Services = () => {
  return( 
  <div>
    <SevicesOffer />
    <Expertise />
  </div>
    )
};

export default Services;