// ✅ SEO Metadata
export const metadata = {
  title: "BawdicSoft",
  description: "Generated by BawdicSoft",
  keywords: [
    "your",
    "digital",
    "marketplace",
    "with",
    "assets",
    "world",
    "services",
    "nfts"
  ],
  openGraph: {
    title: "BawdicSoft",
    description: "Generated by BawdicSoft",
    url: "https://www.bawdicsoft.com/nft-marketplace-development",
    siteName: "Sigmantarian",
    images: [
      {
        url: "https://www.bawdicsoft.com/nft-marketplace-development/opengraph-image.jpg",
        width: 1200,
        height: 630,
        alt: "BawdicSoft"
      }
    ],
    type: "website"
  },
  twitter: {
    card: "summary_large_image",
    title: "BawdicSoft",
    description: "Generated by BawdicSoft",
    images: ["https://www.bawdicsoft.com/nft-marketplace-development/twitter-image.jpg"]
  }
};


import BenifiteNftSection from "@/components/services/blockChain/nft/nftMarketPlace/benifitesNFt";
import FullStackSection from "@/components/services/blockChain/nft/nftMarketPlace/fullStackServices";
import HeroSection from "@/components/services/blockChain/nft/nftMarketPlace/heroSection";
import OurServicesSection from "@/components/services/blockChain/nft/nftMarketPlace/ourServices";
import PartnerChoiceSection from "@/components/services/blockChain/nft/nftMarketPlace/partnerChoice";
import TechnologySection from "@/components/services/blockChain/nft/nftMarketPlace/technology";
import TokenSection from "@/components/services/blockChain/nft/nftMarketPlace/token";
import WhyUsSection from "@/components/services/blockChain/nft/nftMarketPlace/whyUs";
import { FC } from "react";

interface nftMarketPlaceDevelpmentProps {}

const NftMarketPlaceDevelpment : FC<nftMarketPlaceDevelpmentProps> = () => {
    return (<div>
        <HeroSection />
        <FullStackSection />
        <BenifiteNftSection />
        <OurServicesSection />
        <WhyUsSection />
        <TokenSection />
        <TechnologySection />
        <PartnerChoiceSection />
    </div>)
}
export default NftMarketPlaceDevelpment;